notebooks/examples/python/QuickstartNotebook.py
I applied the changes from the comments @milos-colic
=> Refactored quick start python notebook

CHANGELOG.md, pom.xml, python/mosaic/__init__.py
Remove SNAPSHOT and generate 0.1.0 release version.
=> v0.1.0 release

docs/source/api/geometry-accessors.rst, docs/source/api/geometry-constructors.rst, docs/source/api/spatial-functions.rst, docs/source/api/spatial-predicates.rst
=> Fix the broken R lang lexer (R is not a recognized lexer, r is).

notebooks/examples/R/QuickstartNotebook.r, notebooks/examples/python/QuickstartNotebook.py, notebooks/examples/scala/QuickstartNotebook.scala
Fixes #125 https://github.com/databrickslabs/mosaic/issues/125
=> [Bug] Example notebook has column named "zone" which actually references NYC borough

notebooks/examples/python/MosaicAndSedona.py, notebooks/examples/scala/MosaicAndSedona.scala, notebooks/examples/sql/MosaicAndSedona.sql
This adds an example notebook for each language of how to use Mosaic together with Sedona
=> Mosaic and Sedona example

src/main/scala/com/databricks/labs/mosaic/expressions/geometry/FlattenPolygons.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/FlattenPolygonBehaviors.scala
=> st_dump bug fix

.github/workflows/codeql-analysis.yml
=> [COMPLICANCE] Added CodeQL scanner

notebooks/examples/R/QuickstartNotebook.r, notebooks/examples/python/OpenStreetMaps/Readme.md, notebooks/examples/python/QuickstartNotebook.py, notebooks/examples/scala/QuickstartNotebook.scala, notebooks/examples/sql/QuickstartNotebook.sql
Fixed some typos in the example notebook section.
=> Fix typos in example notebooks

src/main/scala/com/databricks/labs/mosaic/core/Mosaic.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/MosaicExplodeBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/TestMosaicExplode.scala
=> Fixed line tessellation traversal when first point intersects cell boundary

docs/source/api/spatial-functions.rst, python/mosaic/api/functions.py, python/test/test_functions.py, src/main/scala/com/databricks/labs/mosaic/core/geometry/MosaicGeometry.scala, src/main/scala/com/databricks/labs/mosaic/core/geometry/MosaicGeometryESRI.scala, src/main/scala/com/databricks/labs/mosaic/core/geometry/MosaicGeometryJTS.scala, src/main/scala/com/databricks/labs/mosaic/expressions/geometry/ST_Envelope.scala, src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_EnvelopeBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_EnvelopeTest.scala
=> Implement st_envelope

src/main/scala/com/databricks/labs/mosaic/expressions/format/ConvertTo.scala, src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala
=> Fixed SQL function names for convert_to

src/main/scala/com/databricks/labs/mosaic/models/knn/SpatialKNN.scala, src/test/scala/com/databricks/labs/mosaic/models/knn/SpatialKNNBehaviors.scala
=> Fixed hardcoded landmarks_miid and candidates_miid column names

geotools-plugin/README.md, geotools-plugin/pom.xml, geotools-plugin/src/main/java/com/databricks/geotools/DatabricksDataStoreFactory.java, geotools-plugin/src/main/java/com/databricks/geotools/DatabricksFilterToSQL.java, geotools-plugin/src/main/java/com/databricks/geotools/DatabricksGISLibrary.java, geotools-plugin/src/main/java/com/databricks/geotools/DatabricksSQLDialect.java, geotools-plugin/src/main/java/com/databricks/geotools/LayersList.java, geotools-plugin/src/main/java/com/databricks/geotools/carto/CartoDialect.java, geotools-plugin/src/main/java/com/databricks/geotools/carto/CartoFilterToSQL.java, geotools-plugin/src/main/java/com/databricks/geotools/mosaic/MosaicDialect.java, geotools-plugin/src/main/java/com/databricks/geotools/mosaic/MosaicFilterToSQL.java, geotools-plugin/src/main/java/com/databricks/geotools/sedona/SedonaDialect.java, geotools-plugin/src/main/java/com/databricks/geotools/sedona/SedonaFilterToSQL.java, geotools-plugin/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi, python/setup.cfg
This is the starting point from feature/3 (Mosaic integration) at repo https://github.com/mjohns-databricks/databricks-geotools-plugin. Need to work on tighter use of Mosaic and refine this PR until ready to merge.
=> initial commit for geoserver connector

.github/workflows/pypi-release.yml
The release action was not aligned with the scala build, it was missing a `sudo`.
=> Aligned pypi release action to scala build

docs/code-example-notebooks/spatial-indexes.py, docs/source/usage/grid-indexes.ipynb, docs/source/usage/quickstart.ipynb
=> Fixed grid_polyfill docs

python/mosaic/api/raster.py
=> Fixed python binding for rst_georeference

modules/python/gdal_package/README.md, modules/python/gdal_package/setup.cfg
@milos-colic a few more small tweaks to update urls. This will catch-up with what is in PyPI (no rush).
=> expanded README and updated some URLs

.github/workflows/docs.yml, docs/docs-requirements.txt
=> Add default value to init script.

src/main/scala/com/databricks/labs/mosaic/core/Mosaic.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/GeometryKRingExplodeBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/GeometryKRingExplodeTest.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/MosaicExplodeBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/MosaicExplodeTest.scala
=> Fix the bug described in issue 360 resulting in incomplete coverage

src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala
=> Fixed photon check

notebooks/data/DownloadUPRNsData.py
=> Fix reference to OpenStreetMaps data

CHANGELOG.md, docs/source/usage/installation.rst
Updated Docs to have the same information on DBR support as we recently added to README.
=> CHANGELOG and Docs

README.md, docs/source/index.rst, docs/source/usage/installation.rst
Standardized messaging for docs and README.
=> DBR support changes

src/main/scala/com/databricks/labs/mosaic/core/index/IndexSystem.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/MosaicExplodeBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/index/MosaicExplodeTest.scala
=> Fix coercion of cell geometries.

docs/source/api/raster-format-readers.rst, docs/source/api/raster-functions.rst, docs/source/usage/install-gdal.rst, src/main/scala/com/databricks/labs/mosaic/core/raster/api/GDAL.scala
=> Add new raster capabilities to the docs.

docs/source/api/raster-functions.rst
without this, they render incorrectly or not at all.
=> fix sphinx-tabs indent

CHANGELOG.md, src/main/scala/com/databricks/labs/mosaic/core/raster/api/GDAL.scala, src/main/scala/com/databricks/labs/mosaic/core/raster/gdal/MosaicRasterGDAL.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/Raster1ArgExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/Raster2ArgExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterArray1ArgExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterArray2ArgExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterArrayExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterExpressionSerialization.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterGeneratorExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterTessellateGeneratorExpression.scala, src/main/scala/com/databricks/labs/mosaic/expressions/raster/base/RasterToGridExpression.scala, src/main/scala/com/databricks/labs/mosaic/functions/MosaicExpressionConfig.scala, src/main/scala/com/databricks/labs/mosaic/gdal/MosaicGDAL.scala
Fix GDAL config passing from spark.conf.
Revert logic for base RST_ expressions.
=> Fix the GDAL max cache value.

.github/workflows/build_main.yml, CHANGELOG.md, R/generate_R_bindings.R, README.md, python/mosaic/api/fuse.py, src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala
- With GDAL-Jammy-3 committed to main, was able to adjust a URL in fuse.py.
- Updated README
- Tried (again) and failed to get R bindings to build. This is due to something it doesn't like about rst_fromcontent. For now, R build is commented out. 
- Updated CHANGELOG
=> Gdal jammy 4

docs/code-example-notebooks/predicates.scala, docs/source/api/spatial-predicates.rst, python/mosaic/api/predicates.py, src/main/scala/com/databricks/labs/mosaic/core/geometry/MosaicGeometry.scala, src/main/scala/com/databricks/labs/mosaic/core/geometry/MosaicGeometryJTS.scala, src/main/scala/com/databricks/labs/mosaic/expressions/geometry/ST_Within.scala, src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_WithinBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_WithinTest.scala
=> add st_within

pom.xml, python/mosaic/api/functions.py, python/test/test_vector_functions.py, src/main/scala/com/databricks/labs/mosaic/core/geometry/MosaicGeometry.scala, src/main/scala/com/databricks/labs/mosaic/core/geometry/MosaicGeometryJTS.scala, src/main/scala/com/databricks/labs/mosaic/expressions/geometry/ST_ConcaveHull.scala, src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_ConcaveHullBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_ConcaveHullTest.scala
=> Add support for ST_ConcaveHull.

README.md, docs/source/api/raster-format-readers.rst, docs/source/api/raster-functions.rst, docs/source/api/spatial-functions.rst, docs/source/api/spatial-indexing.rst, docs/source/api/spatial-predicates.rst, docs/source/api/vector-format-readers.rst, docs/source/index.rst, docs/source/usage/automatic-sql-registration.rst, docs/source/usage/install-gdal.rst, docs/source/usage/installation.rst
=> Mjohns 0.4.0 docs 5

docs/source/api/raster-format-readers.rst, docs/source/api/vector-format-readers.rst, docs/source/index.rst, docs/source/usage/installation.rst
formatting. cleanup gdal driver sections.
=> 0.4.0 Docs Cleanup - 7

README.md, docs/source/api/vector-format-readers.rst, docs/source/index.rst, docs/source/usage/automatic-sql-registration.rst, docs/source/usage/install-gdal.rst, docs/source/usage/installation.rst
Based on feedback / needs from customers, added some additional clarifications in docs and added UDF examples of getting layer names, counts, and schema from vector formats as well as testing for zip of zips.
=> Mjohns 0.4.0 docs 9

python/mosaic/api/predicates.py, src/test/scala/com/databricks/labs/mosaic/functions/MosaicContextBehaviors.scala
Python `__all__` update is required in order to make st_within work from Python.
Second change is adding to a Scala test.
=> include `st_within` in python import and scala test (minor)

python/mosaic/api/aggregators.py, src/main/scala/com/databricks/labs/mosaic/expressions/geometry/ST_AsGeojsonTileAgg.scala, src/main/scala/com/databricks/labs/mosaic/expressions/geometry/ST_AsMVTTileAgg.scala, src/main/scala/com/databricks/labs/mosaic/expressions/geometry/base/AsTileExpression.scala, src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_AsGeoJSONTileAggBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_AsGeoJSONTileAggTest.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_AsMVTTileAggBehaviors.scala, src/test/scala/com/databricks/labs/mosaic/expressions/geometry/ST_AsMVTTileAggTest.scala
Add ST_AsMVTTileAgg aggregator function.
Add all bindings.
=> Add ST_AsGeojsonTileAgg aggregator function.

docs/source/api/raster-functions.rst, docs/source/api/spatial-aggregations.rst, docs/source/api/spatial-functions.rst, docs/source/usage/install-gdal.rst
First pass at docs refresh, focuses on:
1. new APIs in 0.4.1
2. documenting available raster configs
3. fixing examples around `st_srid`, `st_setsrid`, and `st_transform`
=> Initial docs refresh for Mosaic 0.4.1.

python/mosaic/api/raster.py, python/test/test_raster_functions.py
=> Fix rst_mapalgebra in python bindings

docs/source/api/raster-functions.rst
Added the driver parameter to the docs for rst_fromcontent
=> rst_fromcontent docs
